// constants/binance-supported-pairs.ts

export const BINANCE_SUPPORTED_PAIRS = [
  'ETH/USDC',
  'ETH/USDT',
  'ETH/BTC',
  'BTC/USDC',
  'BTC/USDT',
  'ARB/USDC',
  'ARB/USDT',
  'USDC/USDT',
  'USDT/DAI',
  'LINK/USDT',
  'LINK/BTC',
  'UNI/USDT',
  'CRV/USDT',
  'LDO/USDT',
  'MATIC/USDT',
  'MATIC/BTC',
  'MATIC/ETH',
  'AAVE/USDT',
  'LPT/USDT',
  'ENS/USDT',
  '1INCH/USDT',
  'COMP/USDT',
  'GRT/USDT',
  'AXL/USDT',
];
